export function createEnemy(overrides = {}) {
  return {
    type: "patrol",
    x: 100,
    y: 48,
    homeX: 100,
    homeY: 48,
    width: 8,
    height: 8,
    health: 2,
    invulnerableTimer: 0,
    invulnerableDuration: 0.6,
    flashInterval: 0.2,
    patrolSpeed: 12,
    chaseSpeed: 22,
    patrolMinX: 88,
    patrolMaxX: 112,
    directionX: 1,
    directionY: 1,
    chaseRange: 36,
    mode: "patrol",
    orbitAngle: 0,
    orbitSpeed: 1.2,
    orbitRadiusX: 10,
    orbitRadiusY: 10,
    shootTimer: 0,
    shotCooldown: 1.2,
    fixedDirection: "down",
    hitPauseTimer: 0,
    alive: true,
    invincible: false,
    nonBlocking: false,
    ...overrides
  };
}
